config/routes.rb
Rails.application.routes.draw do
  resources :builds
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/build.rb
class Build < ApplicationRecord
    has_many :stations
    accepts_nested_attributes_for :stations, allow_destroy: true 
end

app/models/station.rb
class Station < ApplicationRecord
    belongs_to :build ,optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_action :set_build, only: [:show, :edit, :update, :destroy]

  
  def index
    @builds = Build.all
  end

  
  def show
  end

  
  def new
    @build = Build.new
    @station = 2.times{@build.stations.build}
  end

 
  def edit
    @station = 1.times{@build.stations.build}
  end

  
  def create
    @build = Build.new(build_params)

    respond_to do |format|
      if @build.save
        format.html { redirect_to @build, notice: 'Build was successfully created.' }
        format.json { render :show, status: :created, location: @build }
      else
        format.html { render :new }
        format.json { render json: @build.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @build.update(build_params)
        format.html { redirect_to @build, notice: 'Build was successfully updated.' }
        format.json { render :show, status: :ok, location: @build }
      else
        format.html { render :edit }
        format.json { render json: @build.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def destroy
    @build.destroy
    respond_to do |format|
      format.html { redirect_to builds_url, notice: 'Build was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    
    def set_build
      @build = Build.find(params[:id])
    end

   
    def build_params
      params.require(:build).permit(:name, :rent, :address, :age, :remark, stations_attributes: [:route, :age, :property_id, :time, :id, :_destroy])

      
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/views/builds/_form.html.erb
<%= form_with(model: build, local: true) do |form| %>
  <% if build.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(build.errors.count, "error") %> prohibited this build from being saved:</h2>

      <ul>
      <% build.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name ,"物件名" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :rent ,"賃料" %>
    <%= form.number_field :rent %>
  </div>

  <div class="field">
    <%= form.label :address ,"住所" %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :age ,"築年数" %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :remark ,"備考" %>
    <%= form.text_area :remark %>
  </div>

  <hr>
  <%= form.fields_for :stations do |f| %>
    <div class="field">
      <%= f.label :station_route, "路線名" %>
      <%= f.text_field :route %>
    </div>
    <div class="field">
      <%= f.label :station_name, "駅名" %>
      <%= f.text_field :age %>
    </div>
    <div class="field">
      <%= f.label :station_time, "徒歩時間" %>
      <%= f.number_field :time %>
    </div>
  <% end %> 

  <div class="actions">
    <%= form.submit "登録" %>
  </div>
<% end %>

app/views/builds/edit.html.erb
<h1>物件編集</h1>

<%= render 'form', build: @build %>

<%= link_to 'Show', @build %> |
<%= link_to 'Back', builds_path %>

app/views/builds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>物件一覧</h1>

<table>
  <thead>
    <tr>
      <th>物件名</th>
      <th>賃料</th>
      <th>住所</th>
      <th>築年数</th>
      <th>備考</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @builds.each do |build| %>
      <tr>
        <td><%= build.name %></td>
        <td><%= build.rent %></td>
        <td><%= build.address %></td>
        <td><%= build.age %></td>
        <td><%= build.remark %></td>
        <td><%= link_to "詳細", build %></td>
        <td><%= link_to '編集', edit_build_path(build) %></td>
        <td><%= link_to '削除', build, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "物件を登録する", new_build_path %>

app/views/builds/new.html.erb
<h1>閲覧</h1>

<%= render 'form', build: @build %>

<%= link_to "戻る", builds_path %>

app/views/builds/show.html.erb
<p id="notice"><%= notice %></p>


<%= render 'form', build: @build %>

<%= link_to "編集する", edit_build_path(@build) %> |
<%= link_to "戻る", builds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MofKadai</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>